version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis

  app:
    build: src
    ports:
      - "5000:5000"
    links:
      - redis:redis
    depends_on:
      - redis

volumes:
  redis-data:
